name: Cowsay Quote

on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:

jobs:
  moo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - run: npm start
      - run: |
          git add README.md
          git config --global user.email actions@github.com
          git config --global user.name github-actions
          git commit -m "update readme with new quote"
          git push