name: Update Blog Posts

on:
  workflow_dispatch:

jobs:
  update-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
          deno run --allow-net --allow-read --allow-write update-posts.ts
      - run: |
          git add README.md
          git config --global user.email actions@github.com
          git config --global user.name github-actions
          git commit -m "update readme with new blog posts"
          git push